appName: myoption
environment: online
pprofPort: 19140

httpServer:
  - port: 9140
    certFile:
    keyFile:
  - port: 9141
    certFile: configs/server_cert.pem
    keyFile: configs/server_key.pem
#    read_timeout: 6000  # 毫秒
# 可以配置不同等级的log日志
logDir:
  ./logs/
database:
  dsn: postgres://vito@127.0.0.1:5432/stockindex?&sslmode=disable
  driverName: postgres # 支持mysql
redis:
  addr: 127.0.0.1:6379 #服务器
  password: 138678Mm
  db: 1
pulsar:
  serviceUrl: http://localhost:7080