appName: myoption
environment: test
pprofPort: 19130

httpServer:
  - port: 9130
    certFile:
    keyFile:
  - port: 9131
    certFile: configs/keys/server_cert.pem
    keyFile: configs/keys/server_key.pem

#    read_timeout: 6000  # 毫秒
# 可以配置不同等级的log日志
logDir:
  ./logs/
database:
  # TODO type your dsn here
  dsn: postgres://vito@127.0.0.1:5432/myoption?&sslmode=disable
  driverName: postgres # 支持mysql
redis:
  addr: 127.0.0.1:6379 #服务器
  password: # type here password if you have one
  db: 0
