# 仅支持上证A股（股票代码一般600开头）
- symbolCode: 000001
  symbolName: 上证指数
#- symbolCode: 600030
#  symbolName: 中信证券
#- symbolCode: 601099
#  symbolName: 太平洋
#- symbolCode: 601162
#  symbolName: 天风证券
#- symbolCode: 601012
#  symbolName: 隆基绿能
- symbolCode: 601318
  symbolName: 中国平安
#- symbolCode: 600050
#  symbolName: 中国联通
#- symbolCode: 601688
#  symbolName: 华泰证券
#- symbolCode: 601456
#  symbolName: 国联证券
- symbolCode: 600519
  symbolName: 贵州茅台
#- symbolCode: 600906
#  symbolName: 财达证券
#- symbolCode: 600276
#  symbolName: 恒瑞医药
#- symbolCode: 601138
#  symbolName: 工业富联
#- symbolCode: 600150
#  symbolName: 中国船舶
#- symbolCode: 603000
#  symbolName: 人民网
#- symbolCode: 603986
#  symbolName: 兆易创新
#- symbolCode: 601788
#  symbolName: 光大证券
#- symbolCode: 601881
#  symbolName: 中国银河
#- symbolCode: 601888
#  symbolName: 中国中免
#- symbolCode: 600109
#  symbolName: 国金证券
#- symbolCode: 601059
#  symbolName: 信达证券
#- symbolCode: 601901
#  symbolName: 方正证券
#- symbolCode: 600958
#  symbolName: 东方证券
#- symbolCode: 601519
#  symbolName: 大智慧
#- symbolCode: 600570
#  symbolName: 恒生电子
#- symbolCode: 600705
#  symbolName: 中航产融
#- symbolCode: 600155
#  symbolName: 华创云信
#- symbolCode: 600369
#  symbolName: 西南证券
#- symbolCode: 603019
#  symbolName: 中科曙光
- symbolCode: 600036
  symbolName: 招商银行
#- symbolCode: 601555
#  symbolName: 东吴证券
#- symbolCode: 688318
#  symbolName: 财富趋势
#- symbolCode: 601728
#  symbolName: 中国电信
#- symbolCode: 601696
#  symbolName: 中银证券
#- symbolCode: 600837
#  symbolName: 海通证券
#- symbolCode: 601108
#  symbolName: 财通证券
#- symbolCode: 601211
#  symbolName: 国泰君安
#- symbolCode: 601995
#  symbolName: 中金公司
#- symbolCode: 601377
#  symbolName: 兴业证券
#- symbolCode: 601878
#  symbolName: 浙商证券
- symbolCode: 603259
  symbolName: 药明康德